<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addacesso extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('acesso', array(
             'id_acesso' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => true,
             ),
             'usuario' => 
             array(
              'type' => 'string',
              'length' => 45,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
             ),
             'senha' => 
             array(
              'type' => 'string',
              'length' => 45,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
             ),
             'ultimo_acesso' => 
             array(
              'type' => 'timestamp',
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id_acesso',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('acesso');
    }
}