<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('imovel', 'imovel_tipo_imovel_tipo_id_tipo', array(
             'name' => 'imovel_tipo_imovel_tipo_id_tipo',
             'local' => 'tipo',
             'foreign' => 'id_tipo',
             'foreignTable' => 'imovel_tipo',
             ));
        $this->createForeignKey('imovel_detalhe', 'imovel_detalhe_id_imovel_imovel_id_imovel', array(
             'name' => 'imovel_detalhe_id_imovel_imovel_id_imovel',
             'local' => 'id_imovel',
             'foreign' => 'id_imovel',
             'foreignTable' => 'imovel',
             ));
        $this->createForeignKey('imovel_imagem', 'imovel_imagem_id_imovel_imovel_id_imovel', array(
             'name' => 'imovel_imagem_id_imovel_imovel_id_imovel',
             'local' => 'id_imovel',
             'foreign' => 'id_imovel',
             'foreignTable' => 'imovel',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('imovel', 'imovel_tipo_imovel_tipo_id_tipo');
        $this->dropForeignKey('imovel_detalhe', 'imovel_detalhe_id_imovel_imovel_id_imovel');
        $this->dropForeignKey('imovel_imagem', 'imovel_imagem_id_imovel_imovel_id_imovel');
    }
}