<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addimoveltipo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('imovel_tipo', array(
             'id_tipo' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => true,
             ),
             'tipo' => 
             array(
              'type' => 'string',
              'length' => 255,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id_tipo',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('imovel_tipo');
    }
}