<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcorretorsituacao extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('corretor_situacao', array(
             'id_situacao' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => true,
             ),
             'situacao' => 
             array(
              'type' => 'string',
              'length' => 255,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id_situacao',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('corretor_situacao');
    }
}