<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adicionartabelanoticia extends Doctrine_Migration_Base {
	public function up() {
		$this->createTable('noticia',array( 'id_noticia' => array('type' => 'integer',
																															'length' => 8,
																															'unsigned' => false,
																															'notnull' => 1,
																															'primary' => true,
																															'autoincrement' => true),
																				'titulo' => array('type' => 'string',
																													'length' => 255),
																				'texto' => array('type' => 'string'),
																				'adicionado' => array('type' => 'timestamp',
																															'notnull' => true)
																			)
		);
	}
	
	public function down() {
		$this->dropTable('noticia');
	}
}