<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addlancamento extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('imovel', 'lancamento', 'enum', null, array('values' => array('0','1'),
																																 'default' => '0',
																																 'notnull' => true));
	}
	
	public function down() {
		$this->removeColumn('imovel', 'lancamento');
	}
}